=== 1.6. Заміна параметра набором спеціалізованих методів (Replace Parameter with Explicit Methods)

*Проблема*

Метод було розбито на частини, кожна з яких виконується залежно від значення якогось параметра.

[source, java]
----
void setValue(String name, int value) {
  if (name.equals("height")) {
    height = value;
    return;
  }
  if (name.equals("width")) {
    width = value;
    return;
  }
  Assert.shouldNeverReachHere();
}
----

*Рішення*

Витягніть окремі частини методу у власні методи і викликайте їх замість оригінального методу.

[source, java]
----
void setHeight(int arg) {
  height = arg;
}
void setWidth(int arg) {
  width = arg;
}
----

*Причини рефакторингу*

Метод, що містить варіанти виконання, розрісся до грандіозних розмірів. У кожному з таких ланцюжків виконується нетривіальний код. При цьому нові варіанти додаються дуже рідко.

*Переваги*

Покращує читабельність коду. Куди очевидніше, що робить метод startEngine(), ніж setValue("engineEnabled", true).

*Коли не слід застосовувати*

Не варто застосовувати заміну параметра явними методами, якщо метод рідко міняється, а нові варіації усередині нього не додаються.

*Порядок рефакторингу*

. Для кожного варіанту виконання методу створіть свій власний метод. Запускайте ці методи залежно від значення параметра в основному методі.

. Знайдіть усі місця, де викликається оригінальний метод. Підставте туди виклик одного з нових методів залежно від параметра, що передається.

. Коли не залишиться жодного виклику оригінального методу, його можна буде видалити.