== 1. Організація даних

Рефакторинги цієї групи покликані полегшити роботу з даними, замінивши роботу з примітивними типами багатими функціональністю класами.

Крім того, важливим моментом є зменшення зв’язаність між класами, що покращує переносимість класів і шанси їх повторного використання.

=== 1.1. Самоінкапсуляція поля (Self Encapsulate Field)

Самоінкапсуляція відрізняється від звичайної інкапсуляції поля тим, що рефакторинг робиться над приватним полем.

*Проблема*

Ви використовуєте прямий доступ до приватних полів усередині класу.

[source, java]
----
class Range {
  private int low, high;
  boolean includes(int arg) {
    return arg >= low && arg <= high;
  }
}
----

*Рішення*

Створіть геттер і сеттер для поля, і користуйтеся для доступу до поля тільки ними.

[source, java]
----
class Range {
  private int low, high;
  boolean includes(int arg) {
    return arg >= getLow() && arg <= getHigh();
  }
  int getLow() {
    return low;
  }
  int getHigh() {
    return high;
  }
}
----

*Причини рефакторингу*

Буває так, що вам перестає вистачати гнучкості з прямим доступом до приватного поля всередині класу. Ви хочете мати можливість ініціалізувати значення поля при першому запиті або робити якісь операції над новими значеннями поля в момент присвоєння, або робити все це різними способами в підкласах..

*Переваги*

* Непрямий доступ до полів — це коли робота з полем відбувається через методи доступу (геттери і сеттери). Цей підхід відрізняється набагато більшою гнучкістю, ніж прямий доступ до полів.
    ** По-перше, ви можете здійснювати складні операції при отриманні або установці даних в полі. Лінива ініціалізація, валідація значень в полі — усе це легко реалізується всередині геттерів і сеттерів поля.
    ** По-друге, що ще важливіше, ви можете перевизначати геттери і сеттери в підкласах.
* Ви можете взагалі не реалізовувати сеттер для поля. Значення поля задаватиметься тільки в конструкторі, роблячи це поле незмінним для всього періоду життя об’єкта.

*Недоліки*

Коли використовується прямий доступ до полів, код виглядає простіше і наочніше, хоча і втрачає в гнучкості.

*Порядок рефакторингу*

. Створіть геттер (і, опціонально, сеттер) для поля. Вони мають бути захищеними (protected) або публічними (public).
. Знайдіть усі прямі звернення до поля і замініть їх викликами геттера і сеттера.