== 3. Ускладнювачі змін

Ці запахи призводять до того, що при необхідності щось поміняти в одному місці програми, вам доводиться вносити безліч змін в інших місцях. Це серйозно ускладнює і здорожує розвиток програми.

[#_divergent_change_heading]
=== 3.1. Розбіжні модифікації (Divergent Change)

«Розбіжні модифікації» схожі на <<#_shotgun_surgery_heading,Стрільбу дробом>>, але насправді є протилежністю цього запаху. «Розбіжні модифікації» мають місце, коли є один клас, в якому робиться багато різних змін, а «Стрільба дробом» — це одна зміна, що зачіпає одночасно багато класів.

*Симптоми і ознаки*

При внесенні змін до класу доводиться змінювати багато різноманітних методів. Наприклад, для додавання нового виду товару вам буде потрібно змінити методи пошуку, відображення і замовлення товарів.


*Причини появи*

Найчастіше поява розбіжних модифікацій є наслідком поганої структурованості програми або програмування методом копіювання-вставки.

*Лікування*

* Поведінку класу можна розділити на декілька частин за допомогою відокремлення класу.
* Якщо різні класи мають однакову поведінку, можливо, слід об’єднати ці класи, використовуючи наслідування (відокремлення суперкласу і відокремлення підкласу).


*Виграш*

* Покращує організацію коду.
* Зменшує дублювання коду.
* Спрощує його підтримку.

[#_shotgun_surgery_heading]
=== 3.2. Стрільба дробом (Shotgun Surgery)

«Стрільба дробом» схожа на <<#_divergent_change_heading,Розбіжні модифікації>>, але насправді є протилежністю цього запаху. «Розбіжні модифікації» мають місце, коли є один клас, в якому робиться багато різних змін, а «Стрільба дробом» — це одна зміна, що зачіпає одночасно багато класів.

*Симптоми і ознаки*

При виконанні будь-яких модифікацій доводиться вносити безліч дрібних змін у купу класів.

*Причини появи*

Один обов’язок був розділений серед безлічі класів. Це може статися після фанатичного виправлення Розбіжних модифікацій.

*Лікування*

* Винести всі зміни в один клас дозволять переміщення методу і переміщення поля. Якщо для виконання цієї дії немає відповідного класу, то слід заздалегідь створити новий.
* Якщо після винесення коду в один клас в оригінальних класах мало що залишилося, слід спробувати від них позбутися, скориставшись вбудовуванням класу.


*Виграш*

* Покращує організацію коду.
* Зменшує дублювання коду.
* Спрощує підтримку.

=== 3.2. Паралельні ієрархії наслідування (Parallel Inheritance Hierarchies)

*Симптоми і ознаки*

Всякий раз при створенні підкласу якогось класу доводиться створювати ще один підклас для іншого класу.

*Причини появи*

Доки ієрархія була невелика, все було добре. Але з додаванням нових класів вносити зміни ставало все складніше і складніше.

*Лікування*

Ви можете спробувати усунути дублювання паралельних класів в два етапи. По-перше, потрібно змусити екземпляри однієї ієрархії посилатися на екземпляри іншої ієрархії. Потім слід прибрати ієрархію в класі, що посилається, за допомогою переміщення методу і переміщення поля.

*Виграш*

* Зникає дублювання коду.
* Може поліпшити організацію коду.

*Не варто чіпати, якщо...*

Іноді наявність паралельної ієрархії — це необхідне зло, без якого структура коду програми була б ще гірше. Якщо ви виявите, що ваші спроби усунути дублювання призводять до ще більшого погіршення організації коду, то... зупиніть рефакторинг, відкатіть всі внесені зміни, випийте чаю і почніть звикати до цього коду.