== 6. Інші запахи

Нижче наведені особливі запахи, які не попали в жодну з категорій.

=== 6.1. Неповнота бібліотечного класу (Incomplete Library Class)

*Симптоми і ознаки*

https://uk.wikipedia.org/wiki/%D0%91%D1%96%D0%B1%D0%BB%D1%96%D0%BE%D1%82%D0%B5%D0%BA%D0%B0_%D0%BF%D1%96%D0%B4%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC[Бібліотеки] через деякий час перестають задовольняти вимогам користувачів. Найбільш природним рішенням в цьому випадку є внесення змін у бібліотеку, але дуже часто воно виявляється неможливим, оскільки бібліотека закрита для запису.

*Причини появи*

Автор бібліотеки не передбачив можливості, які вам потрібні, або відмовився їх впроваджувати.

*Лікування*

* Якщо потрібно додати пару методів у бібліотечний клас, використовується впровадження зовнішнього методу.
* Якщо потрібно серйозно змінити поведінку класу, використовується впровадження локального розширення.

*Виграш*

Зменшує дублювання коду (замість створення своєї бібліотеки з нуля, ви продовжуєте працювати з готовою бібліотекою).

*Не варто чіпати, якщо...*

Розширення бібліотеки може стати причиною появи додаткового обсягу роботи. Це відбувається в тому випадку, коли зміни в бібліотеці пов’язані зі змінами в коді.