=== 1.2. Об'єднання умовних операторів (Consolidate Conditional Expression)

*Проблема*

У вас є декілька умовних операторів, що ведуть до однакового результату або дії.

[source, java]
----
double disabilityAmount() {
  if (seniority < 2) {
    return 0;
  }
  if (monthsDisabled > 12) {
    return 0;
  }
  if (isPartTime) {
    return 0;
  }
  // Compute the disability amount.
  // ...
}
----

*Рішення*

Об’єднайте всі умови в одному умовному операторі.

[source, java]
----
double disabilityAmount() {
  if (isNotEligibleForDisability()) {
    return 0;
  }
  // Compute the disability amount.
  // ...
}
----

*Причини рефакторингу*

Код містить безліч операторів, що чергуються і виконують однакові дії. Причина розділення операторів неочевидна.

Головна мета об’єднання операторів — відокремити умову оператора в окремий метод, спростивши його розуміння.

*Порядок рефакторингу*

Перш ніж здійснювати рефакторинг, переконайтеся, що в умовах операторів немає «побічних ефектів», або, іншими словами, ці умови не модифікують щось, а тільки повертають значення. Побічні ефекти можуть бути і в коді, який виконується усередині самого оператора. Наприклад, за результатами умови, щось додається до змінної.

. Об’єднайте декілька умов в одному за допомогою операторів і та або. Об’єднання операторів зазвичай робиться за таким правилом:

** Вкладені умови з’єднуються за допомогою оператора і.

** Умови, які йдуть одна за одною, з’єднуються за допомогою оператора або.

. Відокремте метод від умови оператора і назвіть його так, щоб він відображав суть виразу, який перевірявся.

