=== 1.7. Передача усього об'єкта (Preserve Whole Object)

*Проблема*

Метод було розбито на частини, кожна з яких виконується залежно від значення якогось параметра.

[source, java]
----
int low = daysTempRange.getLow();
int high = daysTempRange.getHigh();
boolean withinPlan = plan.withinRange(low, high);
----

*Рішення*

Витягніть окремі частини методу у власні методи і викликайте їх замість оригінального методу.

[source, java]
----
boolean withinPlan = plan.withinRange(daysTempRange);
----

*Причини рефакторингу*

Проблема полягає в тому, що перед викликом вашого методу треба кожного разу викликати методи майбутнього об’єкта-параметра. Якщо метод виклику цих методів або кількість даних, що отримуються для методу, зміниться, то зміни доведеться шукати і вносити в безлічі місць програми.

Замість цього код отримання усіх потрібних даних може зберігатися одному місці — в самому методі.

*Переваги*

* Замість пачки різноманітних параметрів ви бачите один об’єкт із зрозумілою назвою.

* Якщо методу знадобляться ще якісь дані з об’єкта, не треба буде переписувати усі місця, де викликається цей метод, а тільки нутрощі самого методу.

*Недоліки*

В деяких випадках після такого перетворення метод втрачає в універсальності, оскільки він міг отримувати дані з безлічі різних джерел, а в результаті рефакторингу ми обмежуємо круг його застосування тільки для об’єктів з певним інтерфейсом.

*Порядок рефакторингу*

. Створіть параметр в методі для об’єкта, з якого можна отримати потрібні значення.

. Тепер починайте по одному видаляти старі параметри з методу, замінюючи їх в коді викликами відповідних методів об’єкта-параметра. Тестуйте програму після кожної заміни параметра.

. Видаліть код отримання значень з об’єкта-параметра, який стояв перед викликом методу.