=== 1.3. Відокремлення змінної (Extract Variable)

*Проблема*

У вас є складний для розуміння вираз.

[source, java]
----
void renderBanner() {
  if ((platform.toUpperCase().indexOf("MAC") > -1) &&
       (browser.toUpperCase().indexOf("IE") > -1) &&
        wasInitialized() && resize > 0 )
  {
    // do something
  }
}
----

*Рішення*

Помістіть результат виразу або його частини в окремі змінні, що пояснюють суть виразу.

[source, java]
----
void renderBanner() {
  final boolean isMacOs = platform.toUpperCase().indexOf("MAC") > -1;
  final boolean isIE = browser.toUpperCase().indexOf("IE") > -1;
  final boolean wasResized = resize > 0;

  if (isMacOs && isIE && wasInitialized() && wasResized) {
    // do something
  }
}
----

*Причини рефакторингу*

Головна мотивація цього рефакторингу — зробити зрозумілішим складний вираз, розбивши його на проміжні частини. Це може бути:

* Умова оператора if () або частини оператора ?: у C-подібних мовах.
* Довгий арифметичний вираз без проміжних результатів.
* Довге склеювання рядків.

Виділення змінної може стати першим кроком до подальшого відокремлення методу, якщо ви побачите, що виділений вираз використовується і в інших місцях коду.

*Переваги*

Покращує читабельність коду. Намагайтеся дати виділеним змінним хороші назви, які точно відображатимуть суть виразу. Так ви зробите код читабельним і зможете позбутися від зайвих коментарів. Наприклад, customerTaxValue, cityUnemploymentRate, clientSalutationString і так далі.

*Недоліки*

* З’являються додаткові змінні. Але цей мінус компенсується простотою читання коду.
* Під час рефакторингу виразів умовних операторів пам’ятайте про те, що програма зазвичай оптимізує виконання цих виразів і не виконує подальші перевірки, якщо вже можна передбачити фінальний результат. Наприклад, якщо у виразі if (a () || b ()) ... метод a поверне true, то програма не стане виконувати b, позаяк що б він не повернув, результат все одно буде істинним.

Одначе, після вилучення частин цього виразу в змінні, обидва методи будуть викликатися постійно, що може негативно позначитися на швидкодії, особливо якщо ці методи виконують якусь ресурсоємну роботу.

*Порядок рефакторингу*

. Додайте новий рядок перед виразом, що вас цікавить, і оголосіть там нову змінну. Присвойте цій змінній частину складного виразу.
. Замініть частину винесеного виразу новою змінною.
. Повторіть це для всіх складних частин виразу.