=== 1.4. Вбудовування змінної (Inline Temp)

*Проблема*

У вас є локальна змінна, якій присвоюється результат простого виразу (і більше нічого)

[source, java]
----
boolean hasDiscount(Order order) {
  double basePrice = order.basePrice();
  return basePrice > 1000;
}
----

*Рішення*

Замініть звернення до змінної цим виразом.

[source, java]
----
boolean hasDiscount(Order order) {
  return order.basePrice() > 1000;
}
----

*Причини рефакторингу*

Вбудовування локальної змінної майже завжди використовують як частину заміни змінної викликом методу або для полегшення відокремлення методу.

*Переваги*

Сам по собі цей рефакторинг не несе майже ніякої користі. Проте, якщо змінній присвоюється результат виконання якогось методу, у вас є можливість трохи поліпшити читабельність програми, позбавившись від зайвої змінної.

*Недоліки*

Іноді, на перший погляд даремні тимчасові змінні потрібні для кешування, тобто збереження результату якоїсь дорогої операції, що буде використаний в ході роботи кілька разів повторно. Перед тим, як здійснитити рефакторинг, переконаєтеся, що у вашому випадку це не так.

*Порядок рефакторингу*

. Знайдіть усі місця, де використовується змінна, і замініть цю змінну виразом, який їй присвоювався.
. Видаліть оголошення змінної і рядок присвоєння їй значення.