=== 1.8. Заміна методу об'єктом методів (Replace Method with Method Object)

*Проблема*

У вас є довгий метод, в якому локальні змінні так сильно переплетені, що це робить неможливим застосування відокремлення методу.

[source, java]
----
class Order {
  // ...
  public double price() {
    double primaryBasePrice;
    double secondaryBasePrice;
    double tertiaryBasePrice;
    // Perform long computation.
  }
}
----

*Рішення*

Перетворіть метод в окремий клас так, щоб локальні змінні стали полями цього класу. Після цього можна без проблем розділити метод на частини.

[source, java]
----
class Order {
  // ...
  public double price() {
    return new PriceCalculator(this).compute();
  }
}

class PriceCalculator {
  private double primaryBasePrice;
  private double secondaryBasePrice;
  private double tertiaryBasePrice;

  public PriceCalculator(Order order) {
    // Copy relevant information from the
    // order object.
  }

  public double compute() {
    // Perform long computation.
  }
}
----

*Причини рефакторингу*

Метод занадто довгий, і ви не можете його розділити через переплетення локальних змінних, які складно ізолювати одну від одної.

Першим кроком до вирішення проблеми буде виділення всього цього методу в окремий клас і перетворення його локальних змінних на поля.

По-перше, це дозволить вам ізолювати проблему в межах цього класу, а по-друге, розчистить дорогу для розділення великого методу на менші за розміром методи, які, до того ж, не підходили б до контексту оригінального класу.

*Переваги*

Ізоляція довгого методу у власному класі дозволяє зупинити безконтрольне зростання методу. Крім того, дає можливість ділити його на підметоди в рамках свого класу, не засмічуючи службовими методами оригінальний клас.

*Недоліки*

. Створюється ще один клас, підвищуючи загальну складність програми.

*Порядок рефакторингу*

. Створіть новий клас. Дайте йому назву, ґрунтуючись на призначенні методу, над яким проводиться рефакторинг.
. У новому класі створіть приватне поле для зберігання посилання на екземпляр класу, в якому раніше знаходився метод. Це посилання згодом можна використати, щоб взяти з оригінального об’єкта якісь допоміжні дані.
. Створіть окреме приватне поле для кожної локальної змінної методу.
. Створіть конструктор, який приймає в параметрах значення всіх локальних змінних методу, а також ініціалізує відповідні приватні поля.
. Оголосіть основний метод і скопіюйте в нього код оригінального методу, замінивши локальні змінні приватними полями.
. Замініть тіло оригінального методу в початковому класі створенням об’єкта-методу і викликом його основного методу.